<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ $report['title'] }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #111827; }
        h2, h4 { margin: 0; }
        .meta { margin: 10px 0 15px; }
        .summary { margin: 10px 0 15px; }
        .summary span { display: inline-block; margin-right: 12px; }
        table { width: 100%; border-collapse: collapse; }
        th, td { border: 1px solid #d1d5db; padding: 6px; text-align: left; vertical-align: top; }
        th { background: #f3f4f6; }
    </style>
</head>
<body>
    <h2>{{ $school->name }}</h2>
    <h4>{{ $report['title'] }}</h4>

    <div class="meta">
        <div>Date Range: {{ $filters['date_from'] }} to {{ $filters['date_to'] }}</div>
        <div>Generated At: {{ $generatedAt->format('Y-m-d H:i') }}</div>
        <div>Generated By: {{ $generatedBy ?: 'System' }}</div>
    </div>

    <div class="summary">
        @foreach($report['summary'] as $label => $value)
            <span><strong>{{ $label }}:</strong> {{ $value }}</span>
        @endforeach
    </div>

    <table>
        <thead>
            <tr>
                @foreach($report['columns'] as $column)
                    <th>{{ $column }}</th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @forelse($report['rows'] as $row)
                <tr>
                    @foreach($row as $cell)
                        <td>{{ $cell }}</td>
                    @endforeach
                </tr>
            @empty
                <tr><td colspan="{{ count($report['columns']) }}">No records found.</td></tr>
            @endforelse
        </tbody>
    </table>
</body>
</html>
